spring:
  profiles:
    active: local
    include: oauth
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: cos1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true

        spring:
          profiles: google
          security:
            oauth2:
              client:
                registration:
                  google:
                    client-name: google
                    client-id: 856581985208-470l6tn50as5rl9autjmn4joveliv10r.apps.googleusercontent.com
                    client-secret: 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
                    scope:
                      - email
                      - profile
      app:
        auth:
          tokenSecret: TOKEN_SECRET
          tokenExpiry: 1800000
          refreshTokenExpiry: 604800000
          oauth2:
            authorizedRedirectUris:
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# JWT
jwt:
  secret: YOUR_SECRET_KEY
  access-expired: 1800 # 30(분) - 단위 (초)